accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
arch: resnet18
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 256
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_path: data/tiny-imagenet-200
default_root_dir: null
deterministic: true
devices: null
distributed_backend: null
evaluate: false
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: null
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
ipus: null
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.1
max_epochs: 90
max_steps: null
max_time: null
min_epochs: null
min_steps: null
momentum: 0.9
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: true
pretrained: false
process_position: 0
profiler: simple
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 42
sparsity: 0
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 1.0
weight_decay: 0.0001
weights_save_path: null
weights_summary: top
workers: 4
